- name: This playbook will create the vpc in aws
  hosts: localhost
  become: true
  connection: local
  gather_facts: true
  tasks:
    - name: creating the igw on public subnet
      ec2_vpc_igw:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: present
        resource_tags:
          Name: vprofile-public-igw
      register: igw_out

    - name: creating the route table on public subnet
      ec2_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        tags:
          Name: vprofile-pubrt
        subnets:
          - "{{pubsub1_out.subnet.id}}"
          - "{{pubsub2_out.subnet.id}}"
          - "{{pubsub3_out.subnet.id}}"
        routes:
          dest: 0.0.0.0/0
          gateway_id: "{{igw_out.gateway_id}}"
      register: pubRT_out


