- name: This will create the vpc in aws
  hosts: localhost
  become: true
  connection: local
  gather_facts: false
  tasks:
    - name: importing the variables
      include_vars: vars/vpc_setup

    - name: creating the vpc
      ec2_vpc_net:
        name: "{{vpc_name}}"
        region: "{{region}}"
        cidr_block: "{{vpccidr}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
      register: vpcout

    - debug:
        var: vpcout

    - name: creating the public subnet 1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: present
        cidr: "{{pubsub1cidr}}"
        map_public: yes
        tags:
          name: vprofile-public-subnet1
      register: pubsub1out

    - name: creating the public subnet 2
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: present
        cidr: "{{pubsub2cidr}}"
        map_public: yes
        tags:
          name: vprofile-public-subnet2
      register: pubsub2out

    - name: creating the public subnet 3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone3}}"
        state: present
        cidr: "{{pubsub3cidr}}"
        map_public: yes
        tags:
          name: vprofile-public-subnet3
      register: pubsub3out

    - name: creating the private subnet 1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: present
        cidr: "{{prisub1cidr}}"
        tags:
          name: vprofile-private-subnet1
      register: prisub1out

    - name: creating the private subnet 2
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: present
        cidr: "{{prisub2cidr}}"
        tags:
          name: vprofile-private-subnet2
      register: prisub2out

    - name: creating the private subnet 3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone3}}"
        state: present
        cidr: "{{prisub3cidr}}"
        tags:
          name: vprofile-private-subnet3
      register: prisub3out