- name:
  hosts: localhost
  become: true
  connection: local
  gather_facts: false
  tasks:
    - name: Importing the variabes from var dir
      include_vars: vars/vpc_setup

    - name: this will create the vpc
      ec2_vpc_net:
        name: "{{vpc_name}}"
        region: "{{region}}"
        cidr_block: "{[vpccidr}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
      register: vpcout
    - debug:
        var: vpcout
