- name:
  hosts: localhost
  become: true
  connection: local
  gather_facts: false
  tasks:
    - name: importing the variables
      include_vars: vars/vpc_setup

    - name: creating the vpc
      ec2_vpc_net:
        name: "{{vpc_name}}"
        region: "{{region}}"
        cidr_block: "{{vpccidr}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: present
      register: vpcout

    - debug:
        var: vpcout

    - name: creating the public subnet1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: present
        cidr: "{{pubsub1cidr}}"
        map_public: yes
        resource_tags:
          name: vprofile-pubsub1
      register: pubsub1_out

    - name: Creating public subnet2
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: present
        cidr: "{{pubsub2cidr}}"
        map_public: yes
        tags:
          name: public-subnet2
      register: pubsub2_out

    - name: creating public subnet3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone3}}"
        state: present
        cidr: "{{pubsub3cidr}}"
        map_public: yes
        tags:
          name: public-subnet3
      register: pubsub3_out

    - name: creating the private subnet1
      ec2_vpc_subnet:
        vpc_id: "{{vpcid.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: present
        cidr: "{{prisub1cidr}}"
        tags:
          name: private_subnet1
      register: prisub1_out

    - name: creating the private subent 2
      ec2_vpc_subnet:
        vpc_id: "{{vpc.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: present
        cidr: "{{prisub2cidr}}"
        tags:
          name: private_subnet2
      register: prisub2_out

    - name: creating the private subnet 3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone3}}"
        state: present
        cidr: "{{prisub3cidr}}"
        tags:
          name: private_subent3
      register: prisub3_out

