- name: playbook will create the vpc
  hosts: localhost
  become: true
  connection: local
  gather_facts: false
  tasks:
    - name: importing the variables
      include_vars: vars/vpc_setup

    - name: create the vpc in aws
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpccidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: present
      register: vpcout
    - debug:
        var: vpcout

    - name: creating the subnet for vpc
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.id.vpc}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: present
        cidr: "{{pubsub1cidr}}"
        map_public: yes
        resoure_tags:
          name: vprofile-pubsub1
      register: pubsub1_out


