- name: This playbook will create the vpc
  hosts: localhost
  become: true
  connection: local
  gather_facts: false
  tasks:
    - name: Importing the variabes from var dir
      include_vars: vars/vpc_setup

    - name: this will create the vpc
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpccidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: present
      register: vpcout
    - debug:
        var: vpcout

    - name: creating the subnets
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        cidr: "{{pubsub1cidr}}"
        state: present
        map_public: yes
        tags:
          name: vprofile-pubsub1
      register: pubsub1out

    - name: creating the subent2
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        cidr: "{{pubsub2cidr}}"
        az: "{{zone2}}"
        state: present
        map_public: yes
        tags:
          name: vprofile-pubsub2
      register: pubsub2out