- name: This playbook will create the vpc setup in aws
  hosts: localhost
  become: true
  connection: local
  gather_facts: false
  tasks:
    - name: importing the variables
      include_vars: vars/vpc_setup

    - name: creating vpc
      ec2_vpc_net:
        name: "{{vpc_name}}"
        region: "{{region}}"
        cidr_block: "{{vpccidr}}"
        state: present
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
      register: vpcout

    - debug:
        var: vpcout
    - name: creating the public subnet1
      ec2_vpc_subnet:
        vpc_id: "{[vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: present
        cidr: "{{pubsub1cidr}}"
        map_public: yes
        resource_tags:
          Name: vprofile-public-subnet1
      register: pubsub1_out

    - name: creating the public subnet2
      ec2_vpc_subnet:
        vpc_id: "{[vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: present
        cidr: "{[pubsub2cidr}}"
        map_public: yes
        resource_tags:
          Name: vprofile-public-subnet2
      register: pubsub2_out

    - name: creating the public subent3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az:  "{{zone3}}"
        state: present
        cidr: "{{pubsub3cidr}}"
        map_public: yes
        resource_tags:
          Name: vprofile-public-subnet3
      register: pubsub3_out