- name: playbook for vpc setup in aws
  hosts: localhost
  become: true
  connection: local
  gather_facts: false
  tasks:
    - name: importing the variabes
      include_vars: vars/vpc_setup

    - name: create the vpc router
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpccidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpcout
    - debug:
        vars: vpcout


