- name: this playbook will create the vpc in aws
  hosts: localhost
  become: true
  connection: local
  gather_facts: false
  tasks:
    - name: importing the variables
      include_vars: vars/vpc_setup

    - name: setting up vpc and cidr block
      ec2_vpc_net:
        name: "{{vpc_name}}"
        region: "{{region}}"
        state: present
        cidr_block: "{{vpccidr}}"
        tenancy: default
        dns_support: true
        dns_hostnames: true
      register: vpcout

    - debug:
        var: vpcout

    - name: creating the public subent1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: present
        az: "{{zone1}}"
        cidr: "{{pubsub1cidr}}"
        map_public: yes
        tags:
          Name: vprofile-pubsubnet1
      register: pubsub1_out

    - name: creating the public subnet2
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: present
        az: "{{zone2}}"
        cidr: "{{pubsub2cidr}}"
        map_public: true
        tags:
          Name: vprofile-pubsubnet2
      register: pubsub2_out

    - name: creating the public subnet3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: present
        az: "{{zone3}}"
        cidr: "{{pubsub3cidr}}"
        map_public: yes
        tags:
          Name: vprofile-pubsubnet3
      register: pubsub2_out

    - name: creating the private subnet1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: present
        az: "{{zone1}}"
        cidr: "{{prisub1cidr}}"
        tags:
          Name: vprofile-prisubnet1
      register: prisub1_out

    - name: creating the private subnet2
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: present
        az: "{{zone2}}"
        cidr: "{{prisub2cidr}}"
        tags:
          Name: vprofile-prisubnet2
      register: prisub2_out

    - name: creating the private subnet3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: present
        az: "{{zone3}}"
        cidr: "{{prisub3cidr}}"
        tags:
          Name: vprofile-prisubnet3
      register: prisub3_out

    - name:
      ec2_vpc_igw:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: present
        tags:
          Name: vprofile-PubIGW
      register: igw_out

    - name: creating the route table for public subnet
      ec2_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: present
        tags:
          Name: vprofile-pubRT
        subnets:
          - "{{pubsub1cidr.subnet.id}}"
          - "{{pubsub2cidr.subnet.id}}"
          - "{{pubsub3cidr.subnet.id}}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{igw_out.gateway.id}}"
      register: pubrt_out

    - name: creating the nat gateway and allocate the EIP
      ec2_vpc_nat_gateway:
        state: present
        region: "{{region}}"
        wait: true
        if_exist_do_not_create: true
        subnet_id: "{{igw_out.subnet.id}}"
      register: natgw_out

    - name: creating the route table for private subnet
      ec2_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: present
        tags:
          Name: vprofile-pirRT
        subnets:
          - "{{prisub1cidr.subnet.id}}"
          -  "{{prisub2cidr.subnet.id}}"
          -  "{{prisub3cidr.subnet.id}}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{natgw_out.nat_gateway.id}}"
      register: priRT_out

    - debug:
        var: "{{item}}"
      loop:
        - vpcout_vpc_id
        - pubsub1_out.subnet.id
        - pubsud2_out.subnet.id
        - pubsub3_out.subnet.id
        - prisub1_out.subnet.id
        - prisub2_out.subnet.id
        - prisub3_out.subnet.id
        - igw_out.subnet.id
        - pubRT_out.subnet.id
        - priRt_out.subnet.id




