- name: creating the vpc setup in aws
  hosts: localhost
  become: true
  connection: local
  gather_facts: yes
  tasks:
    - name: importing the variables
      include_vars: vars/vpc_setup

    - name: creating the vpc name and cidr block
      ec2_vpc_net:
        name: "{{vpc_id}}"
        region: "{{region}}"
        state: present
        cidr_block: "{{vpccidr}}"
        tenancy: default
        dns_support: true
        dns_hostnames: true
      register: vpcout

    - debug:
        var: vpcout

    - name: creating the public subnet1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: present
        az: "{{zone1}}"
        cidr: "{{pubsub1cidr}}"
        tags:
          Name: vprofile-pubsubnet1
      register: pubsub1_out

    - name: creating the public subnet2
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: present
        az: "{{zone2}}"
        cidr: "{{pubsub2cidr}}"
        map_public: yes
        tags:
          Name: vprofile-pubsubnet2
      register: pubsub2_out

    - name: creating the public subnet3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: present
        az: "{{zone3}}"
        cidr: "{{pubsub3cidr}}"
        map_public: yes
        tags:
          Name: vprofile-pubsubnet3
      register: pubsub3_out

    - name: creating the private subnet1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: present
        az: "{{zone1}}"
        cidr: "{{prisub1cidr}}"
        tags:
          Name: vprofile-prisubnet1
      register: prisub1_out

    - name: creating the private subnet2
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: present
        az: "{{zone2}}"
        cidr: "{{prisub2cidr}}"
        tags:
          Name: vprofile-prisubnet2
      register: prisub2_out

    - name: creating the private subnet3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: present
        az: "{{zone3}}"
        cidr: "{{prisub3cidr}}"
        tags:
          Name: vprofile-prisubnet3
      register: prisub3_out

    - name: creating the internet gateway
      ec2_vpc_igw:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: present
        tags:
          Name: vproifle-IGW
      register: igw_out

    - name: creating the route table in public subnet
      ec2_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: present
        tags:
          Name: vprofile-IGW
        subnets:
          - "{{pubsub1cidr.subnet.id}}"
          - "{{pubsub2cidr.subnet.id}}"
          - "{{pubusub3cidr.subnet.id}}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{igw_out.gateway_id}}"
      register: pubRT_out

    - name: creating the nat gateway and allocate the EIP
      ec2_vpc_nat_gateway:
        state: present
        subnet_id: "{{igw_out."



